scan_timeout = 2000

[character]
success_symbol = "[ï„ ](bold green)"
error_symbol = "[ïœ„](bold red)"
vicmd_symbol = "[î˜«](bold green)"

[aws]
symbol = "îŒ½  "
# format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[cmake]
# format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
# format = "[â± $duration]($style)"

[conda]
symbol = "ï„Œ "
# format = '\[[$symbol$environment]($style)\]'

[crystal]
# format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = "î˜ "
# format = '\[[$symbol($version)]($style)\]'

[deno]
# format = '\[[$symbol($version)]($style)\]'

[directory]
style = "#ba55d3"
read_only = " ï ½"
truncate_to_repo = false

[docker_context]
symbol = "ïŒˆ "
# format = '\[[$symbol$context]($style)\]'

[dotnet]
# format = '\[[$symbol($version)(ğŸ¯ $tfm)]($style)\]'

[elixir]
symbol = "î‰µ "
# format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = "î˜¬ "
# format = '\[[$symbol($version)]($style)\]'

[erlang]
symbol = "î± "
# format = '\[[$symbol($version)]($style)\]'

[gcloud]
# format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = "ï˜ "
# format = '\[[$symbol$branch]($style)\]'

[git_status]
conflicted = "="
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?"
stashed = "ï’"
modified = "!"
staged = '[++\($count\)](green)'
renamed = "Â»"
deleted = "âœ˜"
# format = '([\[$all_status$ahead_behind\]]($style))'


[golang]
symbol = "î˜§ "
# format = '\[[$symbol($version)]($style)\]'

[helm]
# format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = "ï˜ "
# format = '\[[$symbol$branch]($style)\]'

[java]
symbol = "î‰– "
# format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = "î˜¤ "
# format = '\[[$symbol($version)]($style)\]'

[kotlin]
# format = '\[[$symbol($version)]($style)\]'

[kubernetes]
# format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
# format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = "ï¡š "
# format = '\[$symbol[$ram( | $swap)]($style)\]'

[nim]
symbol = "ïš¤ "
# format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = "ï‹œ "
# format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
# format = '\[[$symbol($version)]($style)\]'

[ocaml]
# format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
# format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
symbol = "ï£– "
# format = '\[[$symbol$version]($style)\]'

[perl]
symbol = "î© "
# format = '\[[$symbol($version)]($style)\]'

[php]
symbol = "î˜ˆ "
# format = '\[[$symbol($version)]($style)\]'

[purescript]
# format = '\[[$symbol($version)]($style)\]'

[python]
symbol = "î˜† "
# format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[red]
# format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = "îˆ¾ "
# format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = "î¨ "
# format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = "îœ· "
# format = '\[[$symbol($version)]($style)\]'

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "
# format = '\[[$symbol($version)]($style)\]'

[terraform]
# format = '\[[$symbol$workspace]($style)\]'

[time]
# format = '\[[$time]($style)\]'

[username]
# format = '\[[$user]($style)\]'

[vagrant]
# format = '\[[$symbol($version)]($style)\]'

[vlang]
# format = '\[[$symbol($version)]($style)\]'

[zig]
# format = '\[[$symbol($version)]($style)\]'

